set dotenv-load := true

start *ARGS: build
  ./bin/clox {{ARGS}}

build:
  if [ ! -f CMakeCache.txt ]; then cmake .; fi
  mkdir -p bin
  cmake --build .

format:
  clang-format --style=google -i src/*

clean:
  rm -f CMakeCache.txt
  rm -rf CMakeFiles
  rm -f cmake_install.cmake
  rm -f Makefile
  rm -rf bin
  rm -f *.a

