set dotenv-load := true

CMAKE_BUILD_TYPE := env_var_or_default('CMAKE_BUILD_TYPE', 'Release')

start *ARGS: build
  rlwrap ./bin/clox {{ARGS}}

build:
  cmake -DCMAKE_BUILD_TYPE={{CMAKE_BUILD_TYPE}} .
  mkdir -p bin
  cmake --build .

format:
  clang-format -i src/*

clean:
  rm -f CMakeCache.txt
  rm -rf CMakeFiles
  rm -f cmake_install.cmake
  rm -f Makefile
  rm -rf bin
  rm -f *.a

